version: '3.8'

services:
  api:
    build: .
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8080
      API_DBHOST: mysql
    ports:
      - '8080:8080'

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ads
      POSTGRES_USER: wopwop
      POSTGRES_PASSWORD: wopwop
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local